// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// ==============================================================

extern int TopAdder (
std::complex<float > output[3],
std::complex<float > input1[3][5],
std::complex<float > input2[3]);
