// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xcomplex2dadder.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XComplex2dadder_CfgInitialize(XComplex2dadder *InstancePtr, XComplex2dadder_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Axilites_BaseAddress = ConfigPtr->Axilites_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XComplex2dadder_Start(XComplex2dadder *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XComplex2dadder_ReadReg(InstancePtr->Axilites_BaseAddress, XCOMPLEX2DADDER_AXILITES_ADDR_AP_CTRL) & 0x80;
    XComplex2dadder_WriteReg(InstancePtr->Axilites_BaseAddress, XCOMPLEX2DADDER_AXILITES_ADDR_AP_CTRL, Data | 0x01);
}

u32 XComplex2dadder_IsDone(XComplex2dadder *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XComplex2dadder_ReadReg(InstancePtr->Axilites_BaseAddress, XCOMPLEX2DADDER_AXILITES_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XComplex2dadder_IsIdle(XComplex2dadder *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XComplex2dadder_ReadReg(InstancePtr->Axilites_BaseAddress, XCOMPLEX2DADDER_AXILITES_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XComplex2dadder_IsReady(XComplex2dadder *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XComplex2dadder_ReadReg(InstancePtr->Axilites_BaseAddress, XCOMPLEX2DADDER_AXILITES_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XComplex2dadder_EnableAutoRestart(XComplex2dadder *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XComplex2dadder_WriteReg(InstancePtr->Axilites_BaseAddress, XCOMPLEX2DADDER_AXILITES_ADDR_AP_CTRL, 0x80);
}

void XComplex2dadder_DisableAutoRestart(XComplex2dadder *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XComplex2dadder_WriteReg(InstancePtr->Axilites_BaseAddress, XCOMPLEX2DADDER_AXILITES_ADDR_AP_CTRL, 0);
}

u32 XComplex2dadder_Get_return(XComplex2dadder *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XComplex2dadder_ReadReg(InstancePtr->Axilites_BaseAddress, XCOMPLEX2DADDER_AXILITES_ADDR_AP_RETURN);
    return Data;
}
u32 XComplex2dadder_Get_in1_M_real_V_BaseAddress(XComplex2dadder *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Axilites_BaseAddress + XCOMPLEX2DADDER_AXILITES_ADDR_IN1_M_REAL_V_BASE);
}

u32 XComplex2dadder_Get_in1_M_real_V_HighAddress(XComplex2dadder *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Axilites_BaseAddress + XCOMPLEX2DADDER_AXILITES_ADDR_IN1_M_REAL_V_HIGH);
}

u32 XComplex2dadder_Get_in1_M_real_V_TotalBytes(XComplex2dadder *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XCOMPLEX2DADDER_AXILITES_ADDR_IN1_M_REAL_V_HIGH - XCOMPLEX2DADDER_AXILITES_ADDR_IN1_M_REAL_V_BASE + 1);
}

u32 XComplex2dadder_Get_in1_M_real_V_BitWidth(XComplex2dadder *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCOMPLEX2DADDER_AXILITES_WIDTH_IN1_M_REAL_V;
}

u32 XComplex2dadder_Get_in1_M_real_V_Depth(XComplex2dadder *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCOMPLEX2DADDER_AXILITES_DEPTH_IN1_M_REAL_V;
}

u32 XComplex2dadder_Write_in1_M_real_V_Words(XComplex2dadder *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XCOMPLEX2DADDER_AXILITES_ADDR_IN1_M_REAL_V_HIGH - XCOMPLEX2DADDER_AXILITES_ADDR_IN1_M_REAL_V_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->Axilites_BaseAddress + XCOMPLEX2DADDER_AXILITES_ADDR_IN1_M_REAL_V_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XComplex2dadder_Read_in1_M_real_V_Words(XComplex2dadder *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XCOMPLEX2DADDER_AXILITES_ADDR_IN1_M_REAL_V_HIGH - XCOMPLEX2DADDER_AXILITES_ADDR_IN1_M_REAL_V_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->Axilites_BaseAddress + XCOMPLEX2DADDER_AXILITES_ADDR_IN1_M_REAL_V_BASE + (offset + i)*4);
    }
    return length;
}

u32 XComplex2dadder_Write_in1_M_real_V_Bytes(XComplex2dadder *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XCOMPLEX2DADDER_AXILITES_ADDR_IN1_M_REAL_V_HIGH - XCOMPLEX2DADDER_AXILITES_ADDR_IN1_M_REAL_V_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->Axilites_BaseAddress + XCOMPLEX2DADDER_AXILITES_ADDR_IN1_M_REAL_V_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XComplex2dadder_Read_in1_M_real_V_Bytes(XComplex2dadder *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XCOMPLEX2DADDER_AXILITES_ADDR_IN1_M_REAL_V_HIGH - XCOMPLEX2DADDER_AXILITES_ADDR_IN1_M_REAL_V_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->Axilites_BaseAddress + XCOMPLEX2DADDER_AXILITES_ADDR_IN1_M_REAL_V_BASE + offset + i);
    }
    return length;
}

u32 XComplex2dadder_Get_in1_M_imag_V_BaseAddress(XComplex2dadder *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Axilites_BaseAddress + XCOMPLEX2DADDER_AXILITES_ADDR_IN1_M_IMAG_V_BASE);
}

u32 XComplex2dadder_Get_in1_M_imag_V_HighAddress(XComplex2dadder *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Axilites_BaseAddress + XCOMPLEX2DADDER_AXILITES_ADDR_IN1_M_IMAG_V_HIGH);
}

u32 XComplex2dadder_Get_in1_M_imag_V_TotalBytes(XComplex2dadder *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XCOMPLEX2DADDER_AXILITES_ADDR_IN1_M_IMAG_V_HIGH - XCOMPLEX2DADDER_AXILITES_ADDR_IN1_M_IMAG_V_BASE + 1);
}

u32 XComplex2dadder_Get_in1_M_imag_V_BitWidth(XComplex2dadder *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCOMPLEX2DADDER_AXILITES_WIDTH_IN1_M_IMAG_V;
}

u32 XComplex2dadder_Get_in1_M_imag_V_Depth(XComplex2dadder *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCOMPLEX2DADDER_AXILITES_DEPTH_IN1_M_IMAG_V;
}

u32 XComplex2dadder_Write_in1_M_imag_V_Words(XComplex2dadder *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XCOMPLEX2DADDER_AXILITES_ADDR_IN1_M_IMAG_V_HIGH - XCOMPLEX2DADDER_AXILITES_ADDR_IN1_M_IMAG_V_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->Axilites_BaseAddress + XCOMPLEX2DADDER_AXILITES_ADDR_IN1_M_IMAG_V_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XComplex2dadder_Read_in1_M_imag_V_Words(XComplex2dadder *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XCOMPLEX2DADDER_AXILITES_ADDR_IN1_M_IMAG_V_HIGH - XCOMPLEX2DADDER_AXILITES_ADDR_IN1_M_IMAG_V_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->Axilites_BaseAddress + XCOMPLEX2DADDER_AXILITES_ADDR_IN1_M_IMAG_V_BASE + (offset + i)*4);
    }
    return length;
}

u32 XComplex2dadder_Write_in1_M_imag_V_Bytes(XComplex2dadder *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XCOMPLEX2DADDER_AXILITES_ADDR_IN1_M_IMAG_V_HIGH - XCOMPLEX2DADDER_AXILITES_ADDR_IN1_M_IMAG_V_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->Axilites_BaseAddress + XCOMPLEX2DADDER_AXILITES_ADDR_IN1_M_IMAG_V_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XComplex2dadder_Read_in1_M_imag_V_Bytes(XComplex2dadder *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XCOMPLEX2DADDER_AXILITES_ADDR_IN1_M_IMAG_V_HIGH - XCOMPLEX2DADDER_AXILITES_ADDR_IN1_M_IMAG_V_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->Axilites_BaseAddress + XCOMPLEX2DADDER_AXILITES_ADDR_IN1_M_IMAG_V_BASE + offset + i);
    }
    return length;
}

u32 XComplex2dadder_Get_in2_M_real_V_BaseAddress(XComplex2dadder *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Axilites_BaseAddress + XCOMPLEX2DADDER_AXILITES_ADDR_IN2_M_REAL_V_BASE);
}

u32 XComplex2dadder_Get_in2_M_real_V_HighAddress(XComplex2dadder *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Axilites_BaseAddress + XCOMPLEX2DADDER_AXILITES_ADDR_IN2_M_REAL_V_HIGH);
}

u32 XComplex2dadder_Get_in2_M_real_V_TotalBytes(XComplex2dadder *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XCOMPLEX2DADDER_AXILITES_ADDR_IN2_M_REAL_V_HIGH - XCOMPLEX2DADDER_AXILITES_ADDR_IN2_M_REAL_V_BASE + 1);
}

u32 XComplex2dadder_Get_in2_M_real_V_BitWidth(XComplex2dadder *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCOMPLEX2DADDER_AXILITES_WIDTH_IN2_M_REAL_V;
}

u32 XComplex2dadder_Get_in2_M_real_V_Depth(XComplex2dadder *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCOMPLEX2DADDER_AXILITES_DEPTH_IN2_M_REAL_V;
}

u32 XComplex2dadder_Write_in2_M_real_V_Words(XComplex2dadder *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XCOMPLEX2DADDER_AXILITES_ADDR_IN2_M_REAL_V_HIGH - XCOMPLEX2DADDER_AXILITES_ADDR_IN2_M_REAL_V_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->Axilites_BaseAddress + XCOMPLEX2DADDER_AXILITES_ADDR_IN2_M_REAL_V_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XComplex2dadder_Read_in2_M_real_V_Words(XComplex2dadder *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XCOMPLEX2DADDER_AXILITES_ADDR_IN2_M_REAL_V_HIGH - XCOMPLEX2DADDER_AXILITES_ADDR_IN2_M_REAL_V_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->Axilites_BaseAddress + XCOMPLEX2DADDER_AXILITES_ADDR_IN2_M_REAL_V_BASE + (offset + i)*4);
    }
    return length;
}

u32 XComplex2dadder_Write_in2_M_real_V_Bytes(XComplex2dadder *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XCOMPLEX2DADDER_AXILITES_ADDR_IN2_M_REAL_V_HIGH - XCOMPLEX2DADDER_AXILITES_ADDR_IN2_M_REAL_V_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->Axilites_BaseAddress + XCOMPLEX2DADDER_AXILITES_ADDR_IN2_M_REAL_V_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XComplex2dadder_Read_in2_M_real_V_Bytes(XComplex2dadder *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XCOMPLEX2DADDER_AXILITES_ADDR_IN2_M_REAL_V_HIGH - XCOMPLEX2DADDER_AXILITES_ADDR_IN2_M_REAL_V_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->Axilites_BaseAddress + XCOMPLEX2DADDER_AXILITES_ADDR_IN2_M_REAL_V_BASE + offset + i);
    }
    return length;
}

u32 XComplex2dadder_Get_in2_M_imag_V_BaseAddress(XComplex2dadder *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Axilites_BaseAddress + XCOMPLEX2DADDER_AXILITES_ADDR_IN2_M_IMAG_V_BASE);
}

u32 XComplex2dadder_Get_in2_M_imag_V_HighAddress(XComplex2dadder *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Axilites_BaseAddress + XCOMPLEX2DADDER_AXILITES_ADDR_IN2_M_IMAG_V_HIGH);
}

u32 XComplex2dadder_Get_in2_M_imag_V_TotalBytes(XComplex2dadder *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XCOMPLEX2DADDER_AXILITES_ADDR_IN2_M_IMAG_V_HIGH - XCOMPLEX2DADDER_AXILITES_ADDR_IN2_M_IMAG_V_BASE + 1);
}

u32 XComplex2dadder_Get_in2_M_imag_V_BitWidth(XComplex2dadder *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCOMPLEX2DADDER_AXILITES_WIDTH_IN2_M_IMAG_V;
}

u32 XComplex2dadder_Get_in2_M_imag_V_Depth(XComplex2dadder *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCOMPLEX2DADDER_AXILITES_DEPTH_IN2_M_IMAG_V;
}

u32 XComplex2dadder_Write_in2_M_imag_V_Words(XComplex2dadder *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XCOMPLEX2DADDER_AXILITES_ADDR_IN2_M_IMAG_V_HIGH - XCOMPLEX2DADDER_AXILITES_ADDR_IN2_M_IMAG_V_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->Axilites_BaseAddress + XCOMPLEX2DADDER_AXILITES_ADDR_IN2_M_IMAG_V_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XComplex2dadder_Read_in2_M_imag_V_Words(XComplex2dadder *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XCOMPLEX2DADDER_AXILITES_ADDR_IN2_M_IMAG_V_HIGH - XCOMPLEX2DADDER_AXILITES_ADDR_IN2_M_IMAG_V_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->Axilites_BaseAddress + XCOMPLEX2DADDER_AXILITES_ADDR_IN2_M_IMAG_V_BASE + (offset + i)*4);
    }
    return length;
}

u32 XComplex2dadder_Write_in2_M_imag_V_Bytes(XComplex2dadder *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XCOMPLEX2DADDER_AXILITES_ADDR_IN2_M_IMAG_V_HIGH - XCOMPLEX2DADDER_AXILITES_ADDR_IN2_M_IMAG_V_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->Axilites_BaseAddress + XCOMPLEX2DADDER_AXILITES_ADDR_IN2_M_IMAG_V_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XComplex2dadder_Read_in2_M_imag_V_Bytes(XComplex2dadder *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XCOMPLEX2DADDER_AXILITES_ADDR_IN2_M_IMAG_V_HIGH - XCOMPLEX2DADDER_AXILITES_ADDR_IN2_M_IMAG_V_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->Axilites_BaseAddress + XCOMPLEX2DADDER_AXILITES_ADDR_IN2_M_IMAG_V_BASE + offset + i);
    }
    return length;
}

void XComplex2dadder_InterruptGlobalEnable(XComplex2dadder *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XComplex2dadder_WriteReg(InstancePtr->Axilites_BaseAddress, XCOMPLEX2DADDER_AXILITES_ADDR_GIE, 1);
}

void XComplex2dadder_InterruptGlobalDisable(XComplex2dadder *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XComplex2dadder_WriteReg(InstancePtr->Axilites_BaseAddress, XCOMPLEX2DADDER_AXILITES_ADDR_GIE, 0);
}

void XComplex2dadder_InterruptEnable(XComplex2dadder *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XComplex2dadder_ReadReg(InstancePtr->Axilites_BaseAddress, XCOMPLEX2DADDER_AXILITES_ADDR_IER);
    XComplex2dadder_WriteReg(InstancePtr->Axilites_BaseAddress, XCOMPLEX2DADDER_AXILITES_ADDR_IER, Register | Mask);
}

void XComplex2dadder_InterruptDisable(XComplex2dadder *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XComplex2dadder_ReadReg(InstancePtr->Axilites_BaseAddress, XCOMPLEX2DADDER_AXILITES_ADDR_IER);
    XComplex2dadder_WriteReg(InstancePtr->Axilites_BaseAddress, XCOMPLEX2DADDER_AXILITES_ADDR_IER, Register & (~Mask));
}

void XComplex2dadder_InterruptClear(XComplex2dadder *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XComplex2dadder_WriteReg(InstancePtr->Axilites_BaseAddress, XCOMPLEX2DADDER_AXILITES_ADDR_ISR, Mask);
}

u32 XComplex2dadder_InterruptGetEnabled(XComplex2dadder *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XComplex2dadder_ReadReg(InstancePtr->Axilites_BaseAddress, XCOMPLEX2DADDER_AXILITES_ADDR_IER);
}

u32 XComplex2dadder_InterruptGetStatus(XComplex2dadder *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XComplex2dadder_ReadReg(InstancePtr->Axilites_BaseAddress, XCOMPLEX2DADDER_AXILITES_ADDR_ISR);
}

