// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// ==============================================================

extern int complexDoubleAdder (
std::complex<double > in1[7],
std::complex<double > in2[7],
std::complex<double > out[7]);
