// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xcomplexdoubleadder.h"

extern XComplexdoubleadder_Config XComplexdoubleadder_ConfigTable[];

XComplexdoubleadder_Config *XComplexdoubleadder_LookupConfig(u16 DeviceId) {
	XComplexdoubleadder_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XCOMPLEXDOUBLEADDER_NUM_INSTANCES; Index++) {
		if (XComplexdoubleadder_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XComplexdoubleadder_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XComplexdoubleadder_Initialize(XComplexdoubleadder *InstancePtr, u16 DeviceId) {
	XComplexdoubleadder_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XComplexdoubleadder_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XComplexdoubleadder_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

