# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/engrm_000/OneDrive/vivado_HLS/complexAdder/complex2DAdder/impl/vhdl/project.cache/wt [current_project]
set_property parent.project_path C:/Users/engrm_000/OneDrive/vivado_HLS/complexAdder/complex2DAdder/impl/vhdl/project.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_vhdl -library xil_defaultlib {
  C:/Users/engrm_000/OneDrive/vivado_HLS/complexAdder/complex2DAdder/impl/vhdl/complex2DAdder_AXILiteS_s_axi.vhd
  C:/Users/engrm_000/OneDrive/vivado_HLS/complexAdder/complex2DAdder/impl/vhdl/complex2DAdder.vhd
}
read_xdc C:/Users/engrm_000/OneDrive/vivado_HLS/complexAdder/complex2DAdder/impl/vhdl/complex2DAdder.xdc
set_property used_in_implementation false [get_files C:/Users/engrm_000/OneDrive/vivado_HLS/complexAdder/complex2DAdder/impl/vhdl/complex2DAdder.xdc]

synth_design -top complex2DAdder -part xc7z020clg484-1 -no_iobuf -mode out_of_context
write_checkpoint -noxdef complex2DAdder.dcp
catch { report_utilization -file complex2DAdder_utilization_synth.rpt -pb complex2DAdder_utilization_synth.pb }
