# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/engrm_000/OneDrive/vivado_HLS/complexAdder/compleDoubleAdder/impl/vhdl/complexDoubleAdder.xdc

# IP: ip/complexDoubleAdder_ap_dadd_3_full_dsp_64/complexDoubleAdder_ap_dadd_3_full_dsp_64.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==complexDoubleAdder_ap_dadd_3_full_dsp_64 || ORIG_REF_NAME==complexDoubleAdder_ap_dadd_3_full_dsp_64}]
