// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xfloatadder.h"

extern XFloatadder_Config XFloatadder_ConfigTable[];

XFloatadder_Config *XFloatadder_LookupConfig(u16 DeviceId) {
	XFloatadder_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XFLOATADDER_NUM_INSTANCES; Index++) {
		if (XFloatadder_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XFloatadder_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XFloatadder_Initialize(XFloatadder *InstancePtr, u16 DeviceId) {
	XFloatadder_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XFloatadder_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XFloatadder_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

