// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

// AXILiteS
// 0x00 : Control signals
//        bit 0  - ap_start (Read/Write/COH)
//        bit 1  - ap_done (Read/COR)
//        bit 2  - ap_idle (Read)
//        bit 3  - ap_ready (Read)
//        bit 7  - auto_restart (Read/Write)
//        others - reserved
// 0x04 : Global Interrupt Enable Register
//        bit 0  - Global Interrupt Enable (Read/Write)
//        others - reserved
// 0x08 : IP Interrupt Enable Register (Read/Write)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x0c : IP Interrupt Status Register (Read/TOW)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x10 : Data signal of ap_return
//        bit 31~0 - ap_return[31:0] (Read)
// 0x20 ~
// 0x2f : Memory 'in1_V' (3 * 18b)
//        Word n : bit [17:0] - in1_V[n]
//                 others     - reserved
// 0x30 ~
// 0x3f : Memory 'in2_V' (3 * 18b)
//        Word n : bit [17:0] - in2_V[n]
//                 others     - reserved
// 0x40 ~
// 0x4f : Memory 'out_V' (3 * 18b)
//        Word n : bit [17:0] - out_V[n]
//                 others     - reserved
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XFLOATADDER_AXILITES_ADDR_AP_CTRL    0x00
#define XFLOATADDER_AXILITES_ADDR_GIE        0x04
#define XFLOATADDER_AXILITES_ADDR_IER        0x08
#define XFLOATADDER_AXILITES_ADDR_ISR        0x0c
#define XFLOATADDER_AXILITES_ADDR_AP_RETURN  0x10
#define XFLOATADDER_AXILITES_BITS_AP_RETURN  32
#define XFLOATADDER_AXILITES_ADDR_IN1_V_BASE 0x20
#define XFLOATADDER_AXILITES_ADDR_IN1_V_HIGH 0x2f
#define XFLOATADDER_AXILITES_WIDTH_IN1_V     18
#define XFLOATADDER_AXILITES_DEPTH_IN1_V     3
#define XFLOATADDER_AXILITES_ADDR_IN2_V_BASE 0x30
#define XFLOATADDER_AXILITES_ADDR_IN2_V_HIGH 0x3f
#define XFLOATADDER_AXILITES_WIDTH_IN2_V     18
#define XFLOATADDER_AXILITES_DEPTH_IN2_V     3
#define XFLOATADDER_AXILITES_ADDR_OUT_V_BASE 0x40
#define XFLOATADDER_AXILITES_ADDR_OUT_V_HIGH 0x4f
#define XFLOATADDER_AXILITES_WIDTH_OUT_V     18
#define XFLOATADDER_AXILITES_DEPTH_OUT_V     3

