# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/engrm_000/OneDrive/vivado_HLS/complexAdder/OptimizedNoMemory/impl/verilog/TopAdder.xdc

# IP: ip/TopAdder_ap_fadd_3_full_dsp_32/TopAdder_ap_fadd_3_full_dsp_32.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TopAdder_ap_fadd_3_full_dsp_32 || ORIG_REF_NAME==TopAdder_ap_fadd_3_full_dsp_32}]
