# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/engrm_000/OneDrive/vivado_HLS/complexAdder/OptimizedNoMemory/impl/verilog/project.cache/wt [current_project]
set_property parent.project_path C:/Users/engrm_000/OneDrive/vivado_HLS/complexAdder/OptimizedNoMemory/impl/verilog/project.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_ip c:/Users/engrm_000/OneDrive/vivado_HLS/complexAdder/OptimizedNoMemory/impl/verilog/project.srcs/sources_1/ip/TopAdder_ap_fadd_3_full_dsp_32/TopAdder_ap_fadd_3_full_dsp_32.xci
set_property is_locked true [get_files c:/Users/engrm_000/OneDrive/vivado_HLS/complexAdder/OptimizedNoMemory/impl/verilog/project.srcs/sources_1/ip/TopAdder_ap_fadd_3_full_dsp_32/TopAdder_ap_fadd_3_full_dsp_32.xci]

read_verilog -library xil_defaultlib {
  C:/Users/engrm_000/OneDrive/vivado_HLS/complexAdder/OptimizedNoMemory/impl/verilog/TopAdder_AXILiteS_s_axi.v
  C:/Users/engrm_000/OneDrive/vivado_HLS/complexAdder/OptimizedNoMemory/impl/verilog/TopAdder_fadd_32ns_32ns_32_5_full_dsp.v
  C:/Users/engrm_000/OneDrive/vivado_HLS/complexAdder/OptimizedNoMemory/impl/verilog/TopAdder_mux_3to1_sel2_32_1.v
  C:/Users/engrm_000/OneDrive/vivado_HLS/complexAdder/OptimizedNoMemory/impl/verilog/TopAdder.v
}
read_xdc C:/Users/engrm_000/OneDrive/vivado_HLS/complexAdder/OptimizedNoMemory/impl/verilog/TopAdder.xdc
set_property used_in_implementation false [get_files C:/Users/engrm_000/OneDrive/vivado_HLS/complexAdder/OptimizedNoMemory/impl/verilog/TopAdder.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top TopAdder -part xc7z020clg484-1 -no_iobuf -mode out_of_context
write_checkpoint -noxdef TopAdder.dcp
catch { report_utilization -file TopAdder_utilization_synth.rpt -pb TopAdder_utilization_synth.pb }
