// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#include "TopSimple.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic TopSimple::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic TopSimple::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<3> TopSimple::ap_ST_st1_fsm_0 = "1";
const sc_lv<3> TopSimple::ap_ST_pp0_stg0_fsm_1 = "10";
const sc_lv<3> TopSimple::ap_ST_st4_fsm_2 = "100";
const sc_lv<32> TopSimple::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> TopSimple::ap_const_lv1_1 = "1";
const int TopSimple::C_S_AXI_DATA_WIDTH = "100000";
const sc_lv<32> TopSimple::ap_const_lv32_1 = "1";
const sc_lv<1> TopSimple::ap_const_lv1_0 = "0";
const sc_lv<2> TopSimple::ap_const_lv2_0 = "00";
const sc_lv<2> TopSimple::ap_const_lv2_3 = "11";
const sc_lv<2> TopSimple::ap_const_lv2_1 = "1";
const sc_lv<32> TopSimple::ap_const_lv32_2 = "10";

TopSimple::TopSimple(sc_module_name name) : sc_module(name), mVcdFile(0) {
    TopSimple_AXILiteS_s_axi_U = new TopSimple_AXILiteS_s_axi<C_S_AXI_AXILITES_ADDR_WIDTH,C_S_AXI_AXILITES_DATA_WIDTH>("TopSimple_AXILiteS_s_axi_U");
    TopSimple_AXILiteS_s_axi_U->AWVALID(s_axi_AXILiteS_AWVALID);
    TopSimple_AXILiteS_s_axi_U->AWREADY(s_axi_AXILiteS_AWREADY);
    TopSimple_AXILiteS_s_axi_U->AWADDR(s_axi_AXILiteS_AWADDR);
    TopSimple_AXILiteS_s_axi_U->WVALID(s_axi_AXILiteS_WVALID);
    TopSimple_AXILiteS_s_axi_U->WREADY(s_axi_AXILiteS_WREADY);
    TopSimple_AXILiteS_s_axi_U->WDATA(s_axi_AXILiteS_WDATA);
    TopSimple_AXILiteS_s_axi_U->WSTRB(s_axi_AXILiteS_WSTRB);
    TopSimple_AXILiteS_s_axi_U->ARVALID(s_axi_AXILiteS_ARVALID);
    TopSimple_AXILiteS_s_axi_U->ARREADY(s_axi_AXILiteS_ARREADY);
    TopSimple_AXILiteS_s_axi_U->ARADDR(s_axi_AXILiteS_ARADDR);
    TopSimple_AXILiteS_s_axi_U->RVALID(s_axi_AXILiteS_RVALID);
    TopSimple_AXILiteS_s_axi_U->RREADY(s_axi_AXILiteS_RREADY);
    TopSimple_AXILiteS_s_axi_U->RDATA(s_axi_AXILiteS_RDATA);
    TopSimple_AXILiteS_s_axi_U->RRESP(s_axi_AXILiteS_RRESP);
    TopSimple_AXILiteS_s_axi_U->BVALID(s_axi_AXILiteS_BVALID);
    TopSimple_AXILiteS_s_axi_U->BREADY(s_axi_AXILiteS_BREADY);
    TopSimple_AXILiteS_s_axi_U->BRESP(s_axi_AXILiteS_BRESP);
    TopSimple_AXILiteS_s_axi_U->ACLK(ap_clk);
    TopSimple_AXILiteS_s_axi_U->ARESET(ap_rst_n_inv);
    TopSimple_AXILiteS_s_axi_U->ACLK_EN(TopSimple_AXILiteS_s_axi_U_ap_dummy_ce);
    TopSimple_AXILiteS_s_axi_U->ap_start(ap_start);
    TopSimple_AXILiteS_s_axi_U->interrupt(interrupt);
    TopSimple_AXILiteS_s_axi_U->ap_ready(ap_ready);
    TopSimple_AXILiteS_s_axi_U->ap_done(ap_done);
    TopSimple_AXILiteS_s_axi_U->ap_idle(ap_idle);
    TopSimple_AXILiteS_s_axi_U->ap_return(ap_return);
    TopSimple_AXILiteS_s_axi_U->in1_address0(in1_address0);
    TopSimple_AXILiteS_s_axi_U->in1_ce0(in1_ce0);
    TopSimple_AXILiteS_s_axi_U->in1_q0(in1_q0);
    TopSimple_AXILiteS_s_axi_U->in2_address0(in2_address0);
    TopSimple_AXILiteS_s_axi_U->in2_ce0(in2_ce0);
    TopSimple_AXILiteS_s_axi_U->in2_q0(in2_q0);
    TopSimple_AXILiteS_s_axi_U->out_r_address0(out_r_address0);
    TopSimple_AXILiteS_s_axi_U->out_r_ce0(out_r_ce0);
    TopSimple_AXILiteS_s_axi_U->out_r_we0(out_r_we0);
    TopSimple_AXILiteS_s_axi_U->out_r_d0(out_r_d0);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_TopSimple_AXILiteS_s_axi_U_ap_dummy_ce);

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_sig_cseq_ST_st4_fsm_2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_sig_cseq_ST_st4_fsm_2 );

    SC_METHOD(thread_ap_return);
    sensitive << ( ap_sig_cseq_ST_st4_fsm_2 );

    SC_METHOD(thread_ap_rst_n_inv);
    sensitive << ( ap_rst_n );

    SC_METHOD(thread_ap_sig_bdd_141);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_21);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_90);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_cseq_ST_pp0_stg0_fsm_1);
    sensitive << ( ap_sig_bdd_90 );

    SC_METHOD(thread_ap_sig_cseq_ST_st1_fsm_0);
    sensitive << ( ap_sig_bdd_21 );

    SC_METHOD(thread_ap_sig_cseq_ST_st4_fsm_2);
    sensitive << ( ap_sig_bdd_141 );

    SC_METHOD(thread_exitcond_fu_99_p2);
    sensitive << ( index_reg_88 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );

    SC_METHOD(thread_in1_address0);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( tmp_fu_111_p1 );

    SC_METHOD(thread_in1_ce0);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );

    SC_METHOD(thread_in2_address0);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( tmp_fu_111_p1 );

    SC_METHOD(thread_in2_ce0);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );

    SC_METHOD(thread_index_1_fu_105_p2);
    sensitive << ( index_reg_88 );

    SC_METHOD(thread_out_r_address0);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( tmp_reg_133 );

    SC_METHOD(thread_out_r_ce0);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_out_r_d0);
    sensitive << ( in1_q0 );
    sensitive << ( in2_q0 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_out_r_we0);
    sensitive << ( exitcond_reg_124 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_tmp_fu_111_p1);
    sensitive << ( index_reg_88 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( exitcond_fu_99_p2 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    ap_CS_fsm = "001";
    ap_reg_ppiten_pp0_it0 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it1 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "TopSimple_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst_n, "(port)ap_rst_n");
    sc_trace(mVcdFile, s_axi_AXILiteS_AWVALID, "(port)s_axi_AXILiteS_AWVALID");
    sc_trace(mVcdFile, s_axi_AXILiteS_AWREADY, "(port)s_axi_AXILiteS_AWREADY");
    sc_trace(mVcdFile, s_axi_AXILiteS_AWADDR, "(port)s_axi_AXILiteS_AWADDR");
    sc_trace(mVcdFile, s_axi_AXILiteS_WVALID, "(port)s_axi_AXILiteS_WVALID");
    sc_trace(mVcdFile, s_axi_AXILiteS_WREADY, "(port)s_axi_AXILiteS_WREADY");
    sc_trace(mVcdFile, s_axi_AXILiteS_WDATA, "(port)s_axi_AXILiteS_WDATA");
    sc_trace(mVcdFile, s_axi_AXILiteS_WSTRB, "(port)s_axi_AXILiteS_WSTRB");
    sc_trace(mVcdFile, s_axi_AXILiteS_ARVALID, "(port)s_axi_AXILiteS_ARVALID");
    sc_trace(mVcdFile, s_axi_AXILiteS_ARREADY, "(port)s_axi_AXILiteS_ARREADY");
    sc_trace(mVcdFile, s_axi_AXILiteS_ARADDR, "(port)s_axi_AXILiteS_ARADDR");
    sc_trace(mVcdFile, s_axi_AXILiteS_RVALID, "(port)s_axi_AXILiteS_RVALID");
    sc_trace(mVcdFile, s_axi_AXILiteS_RREADY, "(port)s_axi_AXILiteS_RREADY");
    sc_trace(mVcdFile, s_axi_AXILiteS_RDATA, "(port)s_axi_AXILiteS_RDATA");
    sc_trace(mVcdFile, s_axi_AXILiteS_RRESP, "(port)s_axi_AXILiteS_RRESP");
    sc_trace(mVcdFile, s_axi_AXILiteS_BVALID, "(port)s_axi_AXILiteS_BVALID");
    sc_trace(mVcdFile, s_axi_AXILiteS_BREADY, "(port)s_axi_AXILiteS_BREADY");
    sc_trace(mVcdFile, s_axi_AXILiteS_BRESP, "(port)s_axi_AXILiteS_BRESP");
    sc_trace(mVcdFile, interrupt, "(port)interrupt");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_rst_n_inv, "ap_rst_n_inv");
    sc_trace(mVcdFile, ap_start, "ap_start");
    sc_trace(mVcdFile, ap_done, "ap_done");
    sc_trace(mVcdFile, ap_idle, "ap_idle");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st1_fsm_0, "ap_sig_cseq_ST_st1_fsm_0");
    sc_trace(mVcdFile, ap_sig_bdd_21, "ap_sig_bdd_21");
    sc_trace(mVcdFile, ap_ready, "ap_ready");
    sc_trace(mVcdFile, in1_address0, "in1_address0");
    sc_trace(mVcdFile, in1_ce0, "in1_ce0");
    sc_trace(mVcdFile, in1_q0, "in1_q0");
    sc_trace(mVcdFile, in2_address0, "in2_address0");
    sc_trace(mVcdFile, in2_ce0, "in2_ce0");
    sc_trace(mVcdFile, in2_q0, "in2_q0");
    sc_trace(mVcdFile, out_r_address0, "out_r_address0");
    sc_trace(mVcdFile, out_r_ce0, "out_r_ce0");
    sc_trace(mVcdFile, out_r_we0, "out_r_we0");
    sc_trace(mVcdFile, out_r_d0, "out_r_d0");
    sc_trace(mVcdFile, ap_return, "ap_return");
    sc_trace(mVcdFile, TopSimple_AXILiteS_s_axi_U_ap_dummy_ce, "TopSimple_AXILiteS_s_axi_U_ap_dummy_ce");
    sc_trace(mVcdFile, index_reg_88, "index_reg_88");
    sc_trace(mVcdFile, exitcond_fu_99_p2, "exitcond_fu_99_p2");
    sc_trace(mVcdFile, exitcond_reg_124, "exitcond_reg_124");
    sc_trace(mVcdFile, ap_sig_cseq_ST_pp0_stg0_fsm_1, "ap_sig_cseq_ST_pp0_stg0_fsm_1");
    sc_trace(mVcdFile, ap_sig_bdd_90, "ap_sig_bdd_90");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it0, "ap_reg_ppiten_pp0_it0");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it1, "ap_reg_ppiten_pp0_it1");
    sc_trace(mVcdFile, index_1_fu_105_p2, "index_1_fu_105_p2");
    sc_trace(mVcdFile, tmp_fu_111_p1, "tmp_fu_111_p1");
    sc_trace(mVcdFile, tmp_reg_133, "tmp_reg_133");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st4_fsm_2, "ap_sig_cseq_ST_st4_fsm_2");
    sc_trace(mVcdFile, ap_sig_bdd_141, "ap_sig_bdd_141");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
    mHdltvinHandle.open("TopSimple.hdltvin.dat");
    mHdltvoutHandle.open("TopSimple.hdltvout.dat");
}

TopSimple::~TopSimple() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete TopSimple_AXILiteS_s_axi_U;
}

void TopSimple::thread_ap_clk_no_reset_() {
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_st1_fsm_0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
             !esl_seteq<1,1,1>(exitcond_fu_99_p2.read(), ap_const_lv1_0))) {
            ap_reg_ppiten_pp0_it0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                    !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
            ap_reg_ppiten_pp0_it0 = ap_const_logic_1;
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
             esl_seteq<1,1,1>(exitcond_fu_99_p2.read(), ap_const_lv1_0))) {
            ap_reg_ppiten_pp0_it1 = ap_const_logic_1;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                     !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) || 
                    (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
                     !esl_seteq<1,1,1>(exitcond_fu_99_p2.read(), ap_const_lv1_0)))) {
            ap_reg_ppiten_pp0_it1 = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
         esl_seteq<1,1,1>(exitcond_fu_99_p2.read(), ap_const_lv1_0))) {
        index_reg_88 = index_1_fu_105_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        index_reg_88 = ap_const_lv2_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read())) {
        exitcond_reg_124 = exitcond_fu_99_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && esl_seteq<1,1,1>(exitcond_fu_99_p2.read(), ap_const_lv1_0))) {
        tmp_reg_133 = tmp_fu_111_p1.read();
    }
}

void TopSimple::thread_TopSimple_AXILiteS_s_axi_U_ap_dummy_ce() {
    TopSimple_AXILiteS_s_axi_U_ap_dummy_ce = ap_const_logic_1;
}

void TopSimple::thread_ap_done() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_2.read())) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void TopSimple::thread_ap_idle() {
    if ((!esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void TopSimple::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_2.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void TopSimple::thread_ap_return() {
    ap_return = ap_const_lv32_1;
}

void TopSimple::thread_ap_rst_n_inv() {
    ap_rst_n_inv =  (sc_logic) (~ap_rst_n.read());
}

void TopSimple::thread_ap_sig_bdd_141() {
    ap_sig_bdd_141 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(2, 2));
}

void TopSimple::thread_ap_sig_bdd_21() {
    ap_sig_bdd_21 = esl_seteq<1,1,1>(ap_CS_fsm.read().range(0, 0), ap_const_lv1_1);
}

void TopSimple::thread_ap_sig_bdd_90() {
    ap_sig_bdd_90 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(1, 1));
}

void TopSimple::thread_ap_sig_cseq_ST_pp0_stg0_fsm_1() {
    if (ap_sig_bdd_90.read()) {
        ap_sig_cseq_ST_pp0_stg0_fsm_1 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_pp0_stg0_fsm_1 = ap_const_logic_0;
    }
}

void TopSimple::thread_ap_sig_cseq_ST_st1_fsm_0() {
    if (ap_sig_bdd_21.read()) {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    }
}

void TopSimple::thread_ap_sig_cseq_ST_st4_fsm_2() {
    if (ap_sig_bdd_141.read()) {
        ap_sig_cseq_ST_st4_fsm_2 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st4_fsm_2 = ap_const_logic_0;
    }
}

void TopSimple::thread_exitcond_fu_99_p2() {
    exitcond_fu_99_p2 = (!index_reg_88.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<1>(): sc_lv<1>(index_reg_88.read() == ap_const_lv2_3);
}

void TopSimple::thread_in1_address0() {
    in1_address0 =  (sc_lv<2>) (tmp_fu_111_p1.read());
}

void TopSimple::thread_in1_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()))) {
        in1_ce0 = ap_const_logic_1;
    } else {
        in1_ce0 = ap_const_logic_0;
    }
}

void TopSimple::thread_in2_address0() {
    in2_address0 =  (sc_lv<2>) (tmp_fu_111_p1.read());
}

void TopSimple::thread_in2_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()))) {
        in2_ce0 = ap_const_logic_1;
    } else {
        in2_ce0 = ap_const_logic_0;
    }
}

void TopSimple::thread_index_1_fu_105_p2() {
    index_1_fu_105_p2 = (!index_reg_88.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(index_reg_88.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void TopSimple::thread_out_r_address0() {
    out_r_address0 =  (sc_lv<2>) (tmp_reg_133.read());
}

void TopSimple::thread_out_r_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()))) {
        out_r_ce0 = ap_const_logic_1;
    } else {
        out_r_ce0 = ap_const_logic_0;
    }
}

void TopSimple::thread_out_r_d0() {
    out_r_d0 = (!in1_q0.read().is_01() || !in2_q0.read().is_01())? sc_lv<32>(): (sc_biguint<32>(in1_q0.read()) + sc_biguint<32>(in2_q0.read()));
}

void TopSimple::thread_out_r_we0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
          esl_seteq<1,1,1>(exitcond_reg_124.read(), ap_const_lv1_0)))) {
        out_r_we0 = ap_const_logic_1;
    } else {
        out_r_we0 = ap_const_logic_0;
    }
}

void TopSimple::thread_tmp_fu_111_p1() {
    tmp_fu_111_p1 = esl_zext<64,2>(index_reg_88.read());
}

void TopSimple::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if (!esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) {
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            }
            break;
        case 2 : 
            if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && !esl_seteq<1,1,1>(exitcond_fu_99_p2.read(), ap_const_lv1_0))) {
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st4_fsm_2;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_st1_fsm_0;
            break;
        default : 
            ap_NS_fsm = "XXX";
            break;
    }
}

void TopSimple::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst_n\" :  \"" << ap_rst_n.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_AWVALID\" :  \"" << s_axi_AXILiteS_AWVALID.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"s_axi_AXILiteS_AWREADY\" :  \"" << s_axi_AXILiteS_AWREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_AWADDR\" :  \"" << s_axi_AXILiteS_AWADDR.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_WVALID\" :  \"" << s_axi_AXILiteS_WVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_WREADY\" :  \"" << s_axi_AXILiteS_WREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_WDATA\" :  \"" << s_axi_AXILiteS_WDATA.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_WSTRB\" :  \"" << s_axi_AXILiteS_WSTRB.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_ARVALID\" :  \"" << s_axi_AXILiteS_ARVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_ARREADY\" :  \"" << s_axi_AXILiteS_ARREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_ARADDR\" :  \"" << s_axi_AXILiteS_ARADDR.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_RVALID\" :  \"" << s_axi_AXILiteS_RVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_RREADY\" :  \"" << s_axi_AXILiteS_RREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_RDATA\" :  \"" << s_axi_AXILiteS_RDATA.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_RRESP\" :  \"" << s_axi_AXILiteS_RRESP.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_BVALID\" :  \"" << s_axi_AXILiteS_BVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_BREADY\" :  \"" << s_axi_AXILiteS_BREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_BRESP\" :  \"" << s_axi_AXILiteS_BRESP.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"interrupt\" :  \"" << interrupt.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

