// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#ifndef _complexDoubleAdder_HH_
#define _complexDoubleAdder_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "complexDoubleAdder_dadd_64ns_64ns_64_5_full_dsp.h"
#include "complexDoubleAdder_AXILiteS_s_axi.h"

namespace ap_rtl {

template<unsigned int C_S_AXI_AXILITES_ADDR_WIDTH = 9,
         unsigned int C_S_AXI_AXILITES_DATA_WIDTH = 32>
struct complexDoubleAdder : public sc_module {
    // Port declarations 20
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst_n;
    sc_in< sc_logic > s_axi_AXILiteS_AWVALID;
    sc_out< sc_logic > s_axi_AXILiteS_AWREADY;
    sc_in< sc_uint<C_S_AXI_AXILITES_ADDR_WIDTH> > s_axi_AXILiteS_AWADDR;
    sc_in< sc_logic > s_axi_AXILiteS_WVALID;
    sc_out< sc_logic > s_axi_AXILiteS_WREADY;
    sc_in< sc_uint<C_S_AXI_AXILITES_DATA_WIDTH> > s_axi_AXILiteS_WDATA;
    sc_in< sc_uint<C_S_AXI_AXILITES_DATA_WIDTH/8> > s_axi_AXILiteS_WSTRB;
    sc_in< sc_logic > s_axi_AXILiteS_ARVALID;
    sc_out< sc_logic > s_axi_AXILiteS_ARREADY;
    sc_in< sc_uint<C_S_AXI_AXILITES_ADDR_WIDTH> > s_axi_AXILiteS_ARADDR;
    sc_out< sc_logic > s_axi_AXILiteS_RVALID;
    sc_in< sc_logic > s_axi_AXILiteS_RREADY;
    sc_out< sc_uint<C_S_AXI_AXILITES_DATA_WIDTH> > s_axi_AXILiteS_RDATA;
    sc_out< sc_lv<2> > s_axi_AXILiteS_RRESP;
    sc_out< sc_logic > s_axi_AXILiteS_BVALID;
    sc_in< sc_logic > s_axi_AXILiteS_BREADY;
    sc_out< sc_lv<2> > s_axi_AXILiteS_BRESP;
    sc_out< sc_logic > interrupt;


    // Module declarations
    complexDoubleAdder(sc_module_name name);
    SC_HAS_PROCESS(complexDoubleAdder);

    ~complexDoubleAdder();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    complexDoubleAdder_AXILiteS_s_axi<C_S_AXI_AXILITES_ADDR_WIDTH,C_S_AXI_AXILITES_DATA_WIDTH>* complexDoubleAdder_AXILiteS_s_axi_U;
    complexDoubleAdder_dadd_64ns_64ns_64_5_full_dsp<1,5,64,64,64>* complexDoubleAdder_dadd_64ns_64ns_64_5_full_dsp_U0;
    complexDoubleAdder_dadd_64ns_64ns_64_5_full_dsp<1,5,64,64,64>* complexDoubleAdder_dadd_64ns_64ns_64_5_full_dsp_U1;
    sc_signal< sc_logic > ap_rst_n_inv;
    sc_signal< sc_logic > ap_start;
    sc_signal< sc_logic > ap_done;
    sc_signal< sc_logic > ap_idle;
    sc_signal< sc_lv<3> > ap_CS_fsm;
    sc_signal< sc_logic > ap_sig_cseq_ST_st1_fsm_0;
    sc_signal< bool > ap_sig_bdd_21;
    sc_signal< sc_logic > ap_ready;
    sc_signal< sc_lv<3> > in1_M_real_address0;
    sc_signal< sc_logic > in1_M_real_ce0;
    sc_signal< sc_lv<64> > in1_M_real_q0;
    sc_signal< sc_lv<3> > in1_M_imag_address0;
    sc_signal< sc_logic > in1_M_imag_ce0;
    sc_signal< sc_lv<64> > in1_M_imag_q0;
    sc_signal< sc_lv<3> > in2_M_real_address0;
    sc_signal< sc_logic > in2_M_real_ce0;
    sc_signal< sc_lv<64> > in2_M_real_q0;
    sc_signal< sc_lv<3> > in2_M_imag_address0;
    sc_signal< sc_logic > in2_M_imag_ce0;
    sc_signal< sc_lv<64> > in2_M_imag_q0;
    sc_signal< sc_lv<3> > out_M_real_address0;
    sc_signal< sc_logic > out_M_real_ce0;
    sc_signal< sc_logic > out_M_real_we0;
    sc_signal< sc_lv<64> > out_M_real_d0;
    sc_signal< sc_lv<3> > out_M_imag_address0;
    sc_signal< sc_logic > out_M_imag_ce0;
    sc_signal< sc_logic > out_M_imag_we0;
    sc_signal< sc_lv<64> > out_M_imag_d0;
    sc_signal< sc_lv<32> > ap_return;
    sc_signal< sc_logic > complexDoubleAdder_AXILiteS_s_axi_U_ap_dummy_ce;
    sc_signal< sc_lv<3> > index_reg_130;
    sc_signal< sc_lv<1> > exitcond_fu_149_p2;
    sc_signal< sc_lv<1> > exitcond_reg_169;
    sc_signal< sc_logic > ap_sig_cseq_ST_pp0_stg0_fsm_1;
    sc_signal< bool > ap_sig_bdd_106;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it0;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it1;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it2;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it3;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it4;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it5;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it6;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it7;
    sc_signal< sc_lv<1> > ap_reg_ppstg_exitcond_reg_169_pp0_it1;
    sc_signal< sc_lv<1> > ap_reg_ppstg_exitcond_reg_169_pp0_it2;
    sc_signal< sc_lv<1> > ap_reg_ppstg_exitcond_reg_169_pp0_it3;
    sc_signal< sc_lv<1> > ap_reg_ppstg_exitcond_reg_169_pp0_it4;
    sc_signal< sc_lv<1> > ap_reg_ppstg_exitcond_reg_169_pp0_it5;
    sc_signal< sc_lv<1> > ap_reg_ppstg_exitcond_reg_169_pp0_it6;
    sc_signal< sc_lv<3> > index_1_fu_155_p2;
    sc_signal< sc_lv<64> > tmp_fu_161_p1;
    sc_signal< sc_lv<64> > tmp_reg_178;
    sc_signal< sc_lv<64> > ap_reg_ppstg_tmp_reg_178_pp0_it1;
    sc_signal< sc_lv<64> > ap_reg_ppstg_tmp_reg_178_pp0_it2;
    sc_signal< sc_lv<64> > ap_reg_ppstg_tmp_reg_178_pp0_it3;
    sc_signal< sc_lv<64> > ap_reg_ppstg_tmp_reg_178_pp0_it4;
    sc_signal< sc_lv<64> > ap_reg_ppstg_tmp_reg_178_pp0_it5;
    sc_signal< sc_lv<64> > ap_reg_ppstg_tmp_reg_178_pp0_it6;
    sc_signal< sc_lv<64> > in1_M_real_load_reg_204;
    sc_signal< sc_lv<64> > in1_M_imag_load_reg_209;
    sc_signal< sc_lv<64> > in2_M_real_load_reg_214;
    sc_signal< sc_lv<64> > in2_M_imag_load_reg_219;
    sc_signal< sc_lv<64> > grp_fu_141_p2;
    sc_signal< sc_lv<64> > p_r_M_real_reg_224;
    sc_signal< sc_lv<64> > grp_fu_145_p2;
    sc_signal< sc_lv<64> > p_r_M_imag_reg_229;
    sc_signal< sc_logic > grp_fu_141_ce;
    sc_signal< sc_logic > grp_fu_145_ce;
    sc_signal< sc_logic > ap_sig_cseq_ST_st10_fsm_2;
    sc_signal< bool > ap_sig_bdd_223;
    sc_signal< sc_lv<3> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<3> ap_ST_st1_fsm_0;
    static const sc_lv<3> ap_ST_pp0_stg0_fsm_1;
    static const sc_lv<3> ap_ST_st10_fsm_2;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const bool ap_true;
    static const int C_S_AXI_DATA_WIDTH;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<3> ap_const_lv3_0;
    static const sc_lv<3> ap_const_lv3_7;
    static const sc_lv<3> ap_const_lv3_1;
    static const sc_lv<32> ap_const_lv32_2;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_return();
    void thread_ap_rst_n_inv();
    void thread_ap_sig_bdd_106();
    void thread_ap_sig_bdd_21();
    void thread_ap_sig_bdd_223();
    void thread_ap_sig_cseq_ST_pp0_stg0_fsm_1();
    void thread_ap_sig_cseq_ST_st10_fsm_2();
    void thread_ap_sig_cseq_ST_st1_fsm_0();
    void thread_complexDoubleAdder_AXILiteS_s_axi_U_ap_dummy_ce();
    void thread_exitcond_fu_149_p2();
    void thread_grp_fu_141_ce();
    void thread_grp_fu_145_ce();
    void thread_in1_M_imag_address0();
    void thread_in1_M_imag_ce0();
    void thread_in1_M_real_address0();
    void thread_in1_M_real_ce0();
    void thread_in2_M_imag_address0();
    void thread_in2_M_imag_ce0();
    void thread_in2_M_real_address0();
    void thread_in2_M_real_ce0();
    void thread_index_1_fu_155_p2();
    void thread_out_M_imag_address0();
    void thread_out_M_imag_ce0();
    void thread_out_M_imag_d0();
    void thread_out_M_imag_we0();
    void thread_out_M_real_address0();
    void thread_out_M_real_ce0();
    void thread_out_M_real_d0();
    void thread_out_M_real_we0();
    void thread_tmp_fu_161_p1();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
