// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xcomplex2dadder.h"

extern XComplex2dadder_Config XComplex2dadder_ConfigTable[];

XComplex2dadder_Config *XComplex2dadder_LookupConfig(u16 DeviceId) {
	XComplex2dadder_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XCOMPLEX2DADDER_NUM_INSTANCES; Index++) {
		if (XComplex2dadder_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XComplex2dadder_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XComplex2dadder_Initialize(XComplex2dadder *InstancePtr, u16 DeviceId) {
	XComplex2dadder_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XComplex2dadder_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XComplex2dadder_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

