// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// ==============================================================

extern int complex2DAdder (
std::complex<ap_fixed<32, 8, (ap_q_mode) 5, (ap_o_mode)3, 0> > in1[5],
std::complex<ap_fixed<32, 8, (ap_q_mode) 5, (ap_o_mode)3, 0> > in2[5][3],
std::complex<ap_fixed<32, 8, (ap_q_mode) 5, (ap_o_mode)3, 0> > out[5]);
