-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2015.4
-- Copyright (C) 2015 Xilinx Inc. All rights reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity complex2DAdder is
generic (
    C_S_AXI_AXILITES_ADDR_WIDTH : INTEGER := 9;
    C_S_AXI_AXILITES_DATA_WIDTH : INTEGER := 32 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    out_M_real_V_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    out_M_real_V_TVALID : OUT STD_LOGIC;
    out_M_real_V_TREADY : IN STD_LOGIC;
    out_M_imag_V_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    out_M_imag_V_TVALID : OUT STD_LOGIC;
    out_M_imag_V_TREADY : IN STD_LOGIC;
    s_axi_AXILiteS_AWVALID : IN STD_LOGIC;
    s_axi_AXILiteS_AWREADY : OUT STD_LOGIC;
    s_axi_AXILiteS_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_AXILITES_ADDR_WIDTH-1 downto 0);
    s_axi_AXILiteS_WVALID : IN STD_LOGIC;
    s_axi_AXILiteS_WREADY : OUT STD_LOGIC;
    s_axi_AXILiteS_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_AXILITES_DATA_WIDTH-1 downto 0);
    s_axi_AXILiteS_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_AXILITES_DATA_WIDTH/8-1 downto 0);
    s_axi_AXILiteS_ARVALID : IN STD_LOGIC;
    s_axi_AXILiteS_ARREADY : OUT STD_LOGIC;
    s_axi_AXILiteS_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_AXILITES_ADDR_WIDTH-1 downto 0);
    s_axi_AXILiteS_RVALID : OUT STD_LOGIC;
    s_axi_AXILiteS_RREADY : IN STD_LOGIC;
    s_axi_AXILiteS_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_AXILITES_DATA_WIDTH-1 downto 0);
    s_axi_AXILiteS_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_AXILiteS_BVALID : OUT STD_LOGIC;
    s_axi_AXILiteS_BREADY : IN STD_LOGIC;
    s_axi_AXILiteS_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    interrupt : OUT STD_LOGIC );
end;


architecture behav of complex2DAdder is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "complex2DAdder,hls_ip_2015_4,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=5.010000,HLS_SYN_LAT=7,HLS_SYN_TPT=none,HLS_SYN_MEM=8,HLS_SYN_DSP=0,HLS_SYN_FF=399,HLS_SYN_LUT=465}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_st1_fsm_0 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_pp0_stg0_fsm_1 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_st4_fsm_2 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant C_S_AXI_DATA_WIDTH : INTEGER range 63 downto 0 := 20;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv3_5 : STD_LOGIC_VECTOR (2 downto 0) := "101";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv5_2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_start : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_idle : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_sig_cseq_ST_st1_fsm_0 : STD_LOGIC;
    signal ap_sig_bdd_21 : BOOLEAN;
    signal ap_ready : STD_LOGIC;
    signal in1_M_real_V_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal in1_M_real_V_ce0 : STD_LOGIC;
    signal in1_M_real_V_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal in1_M_imag_V_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal in1_M_imag_V_ce0 : STD_LOGIC;
    signal in1_M_imag_V_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal in2_M_real_V_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal in2_M_real_V_ce0 : STD_LOGIC;
    signal in2_M_real_V_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal in2_M_imag_V_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal in2_M_imag_V_ce0 : STD_LOGIC;
    signal in2_M_imag_V_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_return : STD_LOGIC_VECTOR (31 downto 0);
    signal complex2DAdder_AXILiteS_s_axi_U_ap_dummy_ce : STD_LOGIC;
    signal index_reg_130 : STD_LOGIC_VECTOR (2 downto 0);
    signal exitcond1_fu_141_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal exitcond1_reg_203 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_sig_cseq_ST_pp0_stg0_fsm_1 : STD_LOGIC;
    signal ap_sig_bdd_100 : BOOLEAN;
    signal ap_reg_ppiten_pp0_it0 : STD_LOGIC := '0';
    signal ap_sig_ioackin_out_M_real_V_TREADY : STD_LOGIC;
    signal ap_sig_ioackin_out_M_imag_V_TREADY : STD_LOGIC;
    signal ap_reg_ppiten_pp0_it1 : STD_LOGIC := '0';
    signal index_1_fu_147_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_4_cast_fu_183_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_fu_153_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_reg_ioackin_out_M_real_V_TREADY : STD_LOGIC := '0';
    signal ap_reg_ioackin_out_M_imag_V_TREADY : STD_LOGIC := '0';
    signal tmp_2_fu_163_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_cast_fu_159_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_3_fu_171_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_4_fu_177_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_sig_cseq_ST_st4_fsm_2 : STD_LOGIC;
    signal ap_sig_bdd_202 : BOOLEAN;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_sig_bdd_147 : BOOLEAN;

    component complex2DAdder_AXILiteS_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        ap_start : OUT STD_LOGIC;
        interrupt : OUT STD_LOGIC;
        ap_ready : IN STD_LOGIC;
        ap_done : IN STD_LOGIC;
        ap_idle : IN STD_LOGIC;
        ap_return : IN STD_LOGIC_VECTOR (31 downto 0);
        in1_M_real_V_address0 : IN STD_LOGIC_VECTOR (2 downto 0);
        in1_M_real_V_ce0 : IN STD_LOGIC;
        in1_M_real_V_q0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        in1_M_imag_V_address0 : IN STD_LOGIC_VECTOR (2 downto 0);
        in1_M_imag_V_ce0 : IN STD_LOGIC;
        in1_M_imag_V_q0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        in2_M_real_V_address0 : IN STD_LOGIC_VECTOR (3 downto 0);
        in2_M_real_V_ce0 : IN STD_LOGIC;
        in2_M_real_V_q0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        in2_M_imag_V_address0 : IN STD_LOGIC_VECTOR (3 downto 0);
        in2_M_imag_V_ce0 : IN STD_LOGIC;
        in2_M_imag_V_q0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    complex2DAdder_AXILiteS_s_axi_U : component complex2DAdder_AXILiteS_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_AXILITES_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_AXILITES_DATA_WIDTH)
    port map (
        AWVALID => s_axi_AXILiteS_AWVALID,
        AWREADY => s_axi_AXILiteS_AWREADY,
        AWADDR => s_axi_AXILiteS_AWADDR,
        WVALID => s_axi_AXILiteS_WVALID,
        WREADY => s_axi_AXILiteS_WREADY,
        WDATA => s_axi_AXILiteS_WDATA,
        WSTRB => s_axi_AXILiteS_WSTRB,
        ARVALID => s_axi_AXILiteS_ARVALID,
        ARREADY => s_axi_AXILiteS_ARREADY,
        ARADDR => s_axi_AXILiteS_ARADDR,
        RVALID => s_axi_AXILiteS_RVALID,
        RREADY => s_axi_AXILiteS_RREADY,
        RDATA => s_axi_AXILiteS_RDATA,
        RRESP => s_axi_AXILiteS_RRESP,
        BVALID => s_axi_AXILiteS_BVALID,
        BREADY => s_axi_AXILiteS_BREADY,
        BRESP => s_axi_AXILiteS_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => complex2DAdder_AXILiteS_s_axi_U_ap_dummy_ce,
        ap_start => ap_start,
        interrupt => interrupt,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_idle => ap_idle,
        ap_return => ap_return,
        in1_M_real_V_address0 => in1_M_real_V_address0,
        in1_M_real_V_ce0 => in1_M_real_V_ce0,
        in1_M_real_V_q0 => in1_M_real_V_q0,
        in1_M_imag_V_address0 => in1_M_imag_V_address0,
        in1_M_imag_V_ce0 => in1_M_imag_V_ce0,
        in1_M_imag_V_q0 => in1_M_imag_V_q0,
        in2_M_real_V_address0 => in2_M_real_V_address0,
        in2_M_real_V_ce0 => in2_M_real_V_ce0,
        in2_M_real_V_q0 => in2_M_real_V_q0,
        in2_M_imag_V_address0 => in2_M_imag_V_address0,
        in2_M_imag_V_ce0 => in2_M_imag_V_ce0,
        in2_M_imag_V_q0 => in2_M_imag_V_q0);





    -- the current state (ap_CS_fsm) of the state machine. --
    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_st1_fsm_0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    -- ap_reg_ioackin_out_M_imag_V_TREADY assign process. --
    ap_reg_ioackin_out_M_imag_V_TREADY_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_reg_ioackin_out_M_imag_V_TREADY <= ap_const_logic_0;
            else
                if (ap_sig_bdd_147) then
                    if (not(((((exitcond1_reg_203 = ap_const_lv1_0) and (ap_const_logic_0 = ap_sig_ioackin_out_M_real_V_TREADY)) or ((exitcond1_reg_203 = ap_const_lv1_0) and (ap_const_logic_0 = ap_sig_ioackin_out_M_imag_V_TREADY))) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1)))) then 
                        ap_reg_ioackin_out_M_imag_V_TREADY <= ap_const_logic_0;
                    elsif ((ap_const_logic_1 = out_M_imag_V_TREADY)) then 
                        ap_reg_ioackin_out_M_imag_V_TREADY <= ap_const_logic_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    -- ap_reg_ioackin_out_M_real_V_TREADY assign process. --
    ap_reg_ioackin_out_M_real_V_TREADY_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_reg_ioackin_out_M_real_V_TREADY <= ap_const_logic_0;
            else
                if (ap_sig_bdd_147) then
                    if (not(((((exitcond1_reg_203 = ap_const_lv1_0) and (ap_const_logic_0 = ap_sig_ioackin_out_M_real_V_TREADY)) or ((exitcond1_reg_203 = ap_const_lv1_0) and (ap_const_logic_0 = ap_sig_ioackin_out_M_imag_V_TREADY))) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1)))) then 
                        ap_reg_ioackin_out_M_real_V_TREADY <= ap_const_logic_0;
                    elsif ((ap_const_logic_1 = out_M_real_V_TREADY)) then 
                        ap_reg_ioackin_out_M_real_V_TREADY <= ap_const_logic_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    -- ap_reg_ppiten_pp0_it0 assign process. --
    ap_reg_ppiten_pp0_it0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_reg_ppiten_pp0_it0 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_1) and not(((((exitcond1_reg_203 = ap_const_lv1_0) and (ap_const_logic_0 = ap_sig_ioackin_out_M_real_V_TREADY)) or ((exitcond1_reg_203 = ap_const_lv1_0) and (ap_const_logic_0 = ap_sig_ioackin_out_M_imag_V_TREADY))) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1))) and not((exitcond1_fu_141_p2 = ap_const_lv1_0)))) then 
                    ap_reg_ppiten_pp0_it0 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and not((ap_start = ap_const_logic_0)))) then 
                    ap_reg_ppiten_pp0_it0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    -- ap_reg_ppiten_pp0_it1 assign process. --
    ap_reg_ppiten_pp0_it1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_1) and not(((((exitcond1_reg_203 = ap_const_lv1_0) and (ap_const_logic_0 = ap_sig_ioackin_out_M_real_V_TREADY)) or ((exitcond1_reg_203 = ap_const_lv1_0) and (ap_const_logic_0 = ap_sig_ioackin_out_M_imag_V_TREADY))) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1))) and (exitcond1_fu_141_p2 = ap_const_lv1_0))) then 
                    ap_reg_ppiten_pp0_it1 <= ap_const_logic_1;
                elsif ((((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and not((ap_start = ap_const_logic_0))) or ((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_1) and not(((((exitcond1_reg_203 = ap_const_lv1_0) and (ap_const_logic_0 = ap_sig_ioackin_out_M_real_V_TREADY)) or ((exitcond1_reg_203 = ap_const_lv1_0) and (ap_const_logic_0 = ap_sig_ioackin_out_M_imag_V_TREADY))) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1))) and not((exitcond1_fu_141_p2 = ap_const_lv1_0))))) then 
                    ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    -- index_reg_130 assign process. --
    index_reg_130_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_1) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and not(((((exitcond1_reg_203 = ap_const_lv1_0) and (ap_const_logic_0 = ap_sig_ioackin_out_M_real_V_TREADY)) or ((exitcond1_reg_203 = ap_const_lv1_0) and (ap_const_logic_0 = ap_sig_ioackin_out_M_imag_V_TREADY))) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1))) and (exitcond1_fu_141_p2 = ap_const_lv1_0))) then 
                index_reg_130 <= index_1_fu_147_p2;
            elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and not((ap_start = ap_const_logic_0)))) then 
                index_reg_130 <= ap_const_lv3_0;
            end if; 
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_1) and not(((((exitcond1_reg_203 = ap_const_lv1_0) and (ap_const_logic_0 = ap_sig_ioackin_out_M_real_V_TREADY)) or ((exitcond1_reg_203 = ap_const_lv1_0) and (ap_const_logic_0 = ap_sig_ioackin_out_M_imag_V_TREADY))) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1))))) then
                exitcond1_reg_203 <= exitcond1_fu_141_p2;
            end if;
        end if;
    end process;

    -- the next state (ap_NS_fsm) of the state machine. --
    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, exitcond1_fu_141_p2, exitcond1_reg_203, ap_reg_ppiten_pp0_it0, ap_sig_ioackin_out_M_real_V_TREADY, ap_sig_ioackin_out_M_imag_V_TREADY, ap_reg_ppiten_pp0_it1)
    begin
        case ap_CS_fsm is
            when ap_ST_st1_fsm_0 => 
                if (not((ap_start = ap_const_logic_0))) then
                    ap_NS_fsm <= ap_ST_pp0_stg0_fsm_1;
                else
                    ap_NS_fsm <= ap_ST_st1_fsm_0;
                end if;
            when ap_ST_pp0_stg0_fsm_1 => 
                if (not(((ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and not(((((exitcond1_reg_203 = ap_const_lv1_0) and (ap_const_logic_0 = ap_sig_ioackin_out_M_real_V_TREADY)) or ((exitcond1_reg_203 = ap_const_lv1_0) and (ap_const_logic_0 = ap_sig_ioackin_out_M_imag_V_TREADY))) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1))) and not((exitcond1_fu_141_p2 = ap_const_lv1_0))))) then
                    ap_NS_fsm <= ap_ST_pp0_stg0_fsm_1;
                elsif (((ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and not(((((exitcond1_reg_203 = ap_const_lv1_0) and (ap_const_logic_0 = ap_sig_ioackin_out_M_real_V_TREADY)) or ((exitcond1_reg_203 = ap_const_lv1_0) and (ap_const_logic_0 = ap_sig_ioackin_out_M_imag_V_TREADY))) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1))) and not((exitcond1_fu_141_p2 = ap_const_lv1_0)))) then
                    ap_NS_fsm <= ap_ST_st4_fsm_2;
                else
                    ap_NS_fsm <= ap_ST_pp0_stg0_fsm_1;
                end if;
            when ap_ST_st4_fsm_2 => 
                ap_NS_fsm <= ap_ST_st1_fsm_0;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;

    -- ap_done assign process. --
    ap_done_assign_proc : process(ap_sig_cseq_ST_st4_fsm_2)
    begin
        if ((ap_const_logic_1 = ap_sig_cseq_ST_st4_fsm_2)) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    -- ap_idle assign process. --
    ap_idle_assign_proc : process(ap_start, ap_sig_cseq_ST_st1_fsm_0)
    begin
        if ((not((ap_const_logic_1 = ap_start)) and (ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    -- ap_ready assign process. --
    ap_ready_assign_proc : process(ap_sig_cseq_ST_st4_fsm_2)
    begin
        if ((ap_const_logic_1 = ap_sig_cseq_ST_st4_fsm_2)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    ap_return <= ap_const_lv32_0;

    -- ap_rst_n_inv assign process. --
    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;


    -- ap_sig_bdd_100 assign process. --
    ap_sig_bdd_100_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_bdd_100 <= (ap_const_lv1_1 = ap_CS_fsm(1 downto 1));
    end process;


    -- ap_sig_bdd_147 assign process. --
    ap_sig_bdd_147_assign_proc : process(exitcond1_reg_203, ap_sig_cseq_ST_pp0_stg0_fsm_1, ap_reg_ppiten_pp0_it1)
    begin
                ap_sig_bdd_147 <= ((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_1) and (exitcond1_reg_203 = ap_const_lv1_0) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1));
    end process;


    -- ap_sig_bdd_202 assign process. --
    ap_sig_bdd_202_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_bdd_202 <= (ap_const_lv1_1 = ap_CS_fsm(2 downto 2));
    end process;


    -- ap_sig_bdd_21 assign process. --
    ap_sig_bdd_21_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_bdd_21 <= (ap_CS_fsm(0 downto 0) = ap_const_lv1_1);
    end process;


    -- ap_sig_cseq_ST_pp0_stg0_fsm_1 assign process. --
    ap_sig_cseq_ST_pp0_stg0_fsm_1_assign_proc : process(ap_sig_bdd_100)
    begin
        if (ap_sig_bdd_100) then 
            ap_sig_cseq_ST_pp0_stg0_fsm_1 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_pp0_stg0_fsm_1 <= ap_const_logic_0;
        end if; 
    end process;


    -- ap_sig_cseq_ST_st1_fsm_0 assign process. --
    ap_sig_cseq_ST_st1_fsm_0_assign_proc : process(ap_sig_bdd_21)
    begin
        if (ap_sig_bdd_21) then 
            ap_sig_cseq_ST_st1_fsm_0 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st1_fsm_0 <= ap_const_logic_0;
        end if; 
    end process;


    -- ap_sig_cseq_ST_st4_fsm_2 assign process. --
    ap_sig_cseq_ST_st4_fsm_2_assign_proc : process(ap_sig_bdd_202)
    begin
        if (ap_sig_bdd_202) then 
            ap_sig_cseq_ST_st4_fsm_2 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st4_fsm_2 <= ap_const_logic_0;
        end if; 
    end process;


    -- ap_sig_ioackin_out_M_imag_V_TREADY assign process. --
    ap_sig_ioackin_out_M_imag_V_TREADY_assign_proc : process(out_M_imag_V_TREADY, ap_reg_ioackin_out_M_imag_V_TREADY)
    begin
        if ((ap_const_logic_0 = ap_reg_ioackin_out_M_imag_V_TREADY)) then 
            ap_sig_ioackin_out_M_imag_V_TREADY <= out_M_imag_V_TREADY;
        else 
            ap_sig_ioackin_out_M_imag_V_TREADY <= ap_const_logic_1;
        end if; 
    end process;


    -- ap_sig_ioackin_out_M_real_V_TREADY assign process. --
    ap_sig_ioackin_out_M_real_V_TREADY_assign_proc : process(out_M_real_V_TREADY, ap_reg_ioackin_out_M_real_V_TREADY)
    begin
        if ((ap_const_logic_0 = ap_reg_ioackin_out_M_real_V_TREADY)) then 
            ap_sig_ioackin_out_M_real_V_TREADY <= out_M_real_V_TREADY;
        else 
            ap_sig_ioackin_out_M_real_V_TREADY <= ap_const_logic_1;
        end if; 
    end process;

    complex2DAdder_AXILiteS_s_axi_U_ap_dummy_ce <= ap_const_logic_1;
    exitcond1_fu_141_p2 <= "1" when (index_reg_130 = ap_const_lv3_5) else "0";
    in1_M_imag_V_address0 <= tmp_fu_153_p1(3 - 1 downto 0);

    -- in1_M_imag_V_ce0 assign process. --
    in1_M_imag_V_ce0_assign_proc : process(exitcond1_reg_203, ap_sig_cseq_ST_pp0_stg0_fsm_1, ap_reg_ppiten_pp0_it0, ap_sig_ioackin_out_M_real_V_TREADY, ap_sig_ioackin_out_M_imag_V_TREADY, ap_reg_ppiten_pp0_it1)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_1) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and not(((((exitcond1_reg_203 = ap_const_lv1_0) and (ap_const_logic_0 = ap_sig_ioackin_out_M_real_V_TREADY)) or ((exitcond1_reg_203 = ap_const_lv1_0) and (ap_const_logic_0 = ap_sig_ioackin_out_M_imag_V_TREADY))) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1))))) then 
            in1_M_imag_V_ce0 <= ap_const_logic_1;
        else 
            in1_M_imag_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    in1_M_real_V_address0 <= tmp_fu_153_p1(3 - 1 downto 0);

    -- in1_M_real_V_ce0 assign process. --
    in1_M_real_V_ce0_assign_proc : process(exitcond1_reg_203, ap_sig_cseq_ST_pp0_stg0_fsm_1, ap_reg_ppiten_pp0_it0, ap_sig_ioackin_out_M_real_V_TREADY, ap_sig_ioackin_out_M_imag_V_TREADY, ap_reg_ppiten_pp0_it1)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_1) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and not(((((exitcond1_reg_203 = ap_const_lv1_0) and (ap_const_logic_0 = ap_sig_ioackin_out_M_real_V_TREADY)) or ((exitcond1_reg_203 = ap_const_lv1_0) and (ap_const_logic_0 = ap_sig_ioackin_out_M_imag_V_TREADY))) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1))))) then 
            in1_M_real_V_ce0 <= ap_const_logic_1;
        else 
            in1_M_real_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    in2_M_imag_V_address0 <= tmp_4_cast_fu_183_p1(4 - 1 downto 0);

    -- in2_M_imag_V_ce0 assign process. --
    in2_M_imag_V_ce0_assign_proc : process(exitcond1_reg_203, ap_sig_cseq_ST_pp0_stg0_fsm_1, ap_reg_ppiten_pp0_it0, ap_sig_ioackin_out_M_real_V_TREADY, ap_sig_ioackin_out_M_imag_V_TREADY, ap_reg_ppiten_pp0_it1)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_1) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and not(((((exitcond1_reg_203 = ap_const_lv1_0) and (ap_const_logic_0 = ap_sig_ioackin_out_M_real_V_TREADY)) or ((exitcond1_reg_203 = ap_const_lv1_0) and (ap_const_logic_0 = ap_sig_ioackin_out_M_imag_V_TREADY))) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1))))) then 
            in2_M_imag_V_ce0 <= ap_const_logic_1;
        else 
            in2_M_imag_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    in2_M_real_V_address0 <= tmp_4_cast_fu_183_p1(4 - 1 downto 0);

    -- in2_M_real_V_ce0 assign process. --
    in2_M_real_V_ce0_assign_proc : process(exitcond1_reg_203, ap_sig_cseq_ST_pp0_stg0_fsm_1, ap_reg_ppiten_pp0_it0, ap_sig_ioackin_out_M_real_V_TREADY, ap_sig_ioackin_out_M_imag_V_TREADY, ap_reg_ppiten_pp0_it1)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_1) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and not(((((exitcond1_reg_203 = ap_const_lv1_0) and (ap_const_logic_0 = ap_sig_ioackin_out_M_real_V_TREADY)) or ((exitcond1_reg_203 = ap_const_lv1_0) and (ap_const_logic_0 = ap_sig_ioackin_out_M_imag_V_TREADY))) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1))))) then 
            in2_M_real_V_ce0 <= ap_const_logic_1;
        else 
            in2_M_real_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    index_1_fu_147_p2 <= std_logic_vector(unsigned(index_reg_130) + unsigned(ap_const_lv3_1));
    out_M_imag_V_TDATA <= std_logic_vector(unsigned(in1_M_imag_V_q0) + unsigned(in2_M_imag_V_q0));

    -- out_M_imag_V_TVALID assign process. --
    out_M_imag_V_TVALID_assign_proc : process(exitcond1_reg_203, ap_sig_cseq_ST_pp0_stg0_fsm_1, ap_reg_ppiten_pp0_it1, ap_reg_ioackin_out_M_imag_V_TREADY)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_1) and (exitcond1_reg_203 = ap_const_lv1_0) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1) and (ap_const_logic_0 = ap_reg_ioackin_out_M_imag_V_TREADY))) then 
            out_M_imag_V_TVALID <= ap_const_logic_1;
        else 
            out_M_imag_V_TVALID <= ap_const_logic_0;
        end if; 
    end process;

    out_M_real_V_TDATA <= std_logic_vector(unsigned(in1_M_real_V_q0) + unsigned(in2_M_real_V_q0));

    -- out_M_real_V_TVALID assign process. --
    out_M_real_V_TVALID_assign_proc : process(exitcond1_reg_203, ap_sig_cseq_ST_pp0_stg0_fsm_1, ap_reg_ppiten_pp0_it1, ap_reg_ioackin_out_M_real_V_TREADY)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_1) and (exitcond1_reg_203 = ap_const_lv1_0) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1) and (ap_const_logic_0 = ap_reg_ioackin_out_M_real_V_TREADY))) then 
            out_M_real_V_TVALID <= ap_const_logic_1;
        else 
            out_M_real_V_TVALID <= ap_const_logic_0;
        end if; 
    end process;

    tmp_2_fu_163_p3 <= (index_reg_130 & ap_const_lv2_0);
    tmp_3_fu_171_p2 <= std_logic_vector(unsigned(tmp_2_fu_163_p3) - unsigned(tmp_cast_fu_159_p1));
        tmp_4_cast_fu_183_p1 <= std_logic_vector(resize(signed(tmp_4_fu_177_p2),64));

    tmp_4_fu_177_p2 <= std_logic_vector(unsigned(tmp_3_fu_171_p2) + unsigned(ap_const_lv5_2));
    tmp_cast_fu_159_p1 <= std_logic_vector(resize(unsigned(index_reg_130),5));
    tmp_fu_153_p1 <= std_logic_vector(resize(unsigned(index_reg_130),64));
end behav;
