// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xtopsimple.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XTopsimple_CfgInitialize(XTopsimple *InstancePtr, XTopsimple_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Axilites_BaseAddress = ConfigPtr->Axilites_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XTopsimple_Start(XTopsimple *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XTopsimple_ReadReg(InstancePtr->Axilites_BaseAddress, XTOPSIMPLE_AXILITES_ADDR_AP_CTRL) & 0x80;
    XTopsimple_WriteReg(InstancePtr->Axilites_BaseAddress, XTOPSIMPLE_AXILITES_ADDR_AP_CTRL, Data | 0x01);
}

u32 XTopsimple_IsDone(XTopsimple *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XTopsimple_ReadReg(InstancePtr->Axilites_BaseAddress, XTOPSIMPLE_AXILITES_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XTopsimple_IsIdle(XTopsimple *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XTopsimple_ReadReg(InstancePtr->Axilites_BaseAddress, XTOPSIMPLE_AXILITES_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XTopsimple_IsReady(XTopsimple *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XTopsimple_ReadReg(InstancePtr->Axilites_BaseAddress, XTOPSIMPLE_AXILITES_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XTopsimple_EnableAutoRestart(XTopsimple *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XTopsimple_WriteReg(InstancePtr->Axilites_BaseAddress, XTOPSIMPLE_AXILITES_ADDR_AP_CTRL, 0x80);
}

void XTopsimple_DisableAutoRestart(XTopsimple *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XTopsimple_WriteReg(InstancePtr->Axilites_BaseAddress, XTOPSIMPLE_AXILITES_ADDR_AP_CTRL, 0);
}

u32 XTopsimple_Get_return(XTopsimple *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XTopsimple_ReadReg(InstancePtr->Axilites_BaseAddress, XTOPSIMPLE_AXILITES_ADDR_AP_RETURN);
    return Data;
}
u32 XTopsimple_Get_in1_BaseAddress(XTopsimple *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Axilites_BaseAddress + XTOPSIMPLE_AXILITES_ADDR_IN1_BASE);
}

u32 XTopsimple_Get_in1_HighAddress(XTopsimple *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Axilites_BaseAddress + XTOPSIMPLE_AXILITES_ADDR_IN1_HIGH);
}

u32 XTopsimple_Get_in1_TotalBytes(XTopsimple *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XTOPSIMPLE_AXILITES_ADDR_IN1_HIGH - XTOPSIMPLE_AXILITES_ADDR_IN1_BASE + 1);
}

u32 XTopsimple_Get_in1_BitWidth(XTopsimple *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XTOPSIMPLE_AXILITES_WIDTH_IN1;
}

u32 XTopsimple_Get_in1_Depth(XTopsimple *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XTOPSIMPLE_AXILITES_DEPTH_IN1;
}

u32 XTopsimple_Write_in1_Words(XTopsimple *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XTOPSIMPLE_AXILITES_ADDR_IN1_HIGH - XTOPSIMPLE_AXILITES_ADDR_IN1_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->Axilites_BaseAddress + XTOPSIMPLE_AXILITES_ADDR_IN1_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XTopsimple_Read_in1_Words(XTopsimple *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XTOPSIMPLE_AXILITES_ADDR_IN1_HIGH - XTOPSIMPLE_AXILITES_ADDR_IN1_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->Axilites_BaseAddress + XTOPSIMPLE_AXILITES_ADDR_IN1_BASE + (offset + i)*4);
    }
    return length;
}

u32 XTopsimple_Write_in1_Bytes(XTopsimple *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XTOPSIMPLE_AXILITES_ADDR_IN1_HIGH - XTOPSIMPLE_AXILITES_ADDR_IN1_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->Axilites_BaseAddress + XTOPSIMPLE_AXILITES_ADDR_IN1_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XTopsimple_Read_in1_Bytes(XTopsimple *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XTOPSIMPLE_AXILITES_ADDR_IN1_HIGH - XTOPSIMPLE_AXILITES_ADDR_IN1_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->Axilites_BaseAddress + XTOPSIMPLE_AXILITES_ADDR_IN1_BASE + offset + i);
    }
    return length;
}

u32 XTopsimple_Get_in2_BaseAddress(XTopsimple *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Axilites_BaseAddress + XTOPSIMPLE_AXILITES_ADDR_IN2_BASE);
}

u32 XTopsimple_Get_in2_HighAddress(XTopsimple *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Axilites_BaseAddress + XTOPSIMPLE_AXILITES_ADDR_IN2_HIGH);
}

u32 XTopsimple_Get_in2_TotalBytes(XTopsimple *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XTOPSIMPLE_AXILITES_ADDR_IN2_HIGH - XTOPSIMPLE_AXILITES_ADDR_IN2_BASE + 1);
}

u32 XTopsimple_Get_in2_BitWidth(XTopsimple *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XTOPSIMPLE_AXILITES_WIDTH_IN2;
}

u32 XTopsimple_Get_in2_Depth(XTopsimple *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XTOPSIMPLE_AXILITES_DEPTH_IN2;
}

u32 XTopsimple_Write_in2_Words(XTopsimple *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XTOPSIMPLE_AXILITES_ADDR_IN2_HIGH - XTOPSIMPLE_AXILITES_ADDR_IN2_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->Axilites_BaseAddress + XTOPSIMPLE_AXILITES_ADDR_IN2_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XTopsimple_Read_in2_Words(XTopsimple *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XTOPSIMPLE_AXILITES_ADDR_IN2_HIGH - XTOPSIMPLE_AXILITES_ADDR_IN2_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->Axilites_BaseAddress + XTOPSIMPLE_AXILITES_ADDR_IN2_BASE + (offset + i)*4);
    }
    return length;
}

u32 XTopsimple_Write_in2_Bytes(XTopsimple *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XTOPSIMPLE_AXILITES_ADDR_IN2_HIGH - XTOPSIMPLE_AXILITES_ADDR_IN2_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->Axilites_BaseAddress + XTOPSIMPLE_AXILITES_ADDR_IN2_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XTopsimple_Read_in2_Bytes(XTopsimple *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XTOPSIMPLE_AXILITES_ADDR_IN2_HIGH - XTOPSIMPLE_AXILITES_ADDR_IN2_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->Axilites_BaseAddress + XTOPSIMPLE_AXILITES_ADDR_IN2_BASE + offset + i);
    }
    return length;
}

u32 XTopsimple_Get_out_r_BaseAddress(XTopsimple *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Axilites_BaseAddress + XTOPSIMPLE_AXILITES_ADDR_OUT_R_BASE);
}

u32 XTopsimple_Get_out_r_HighAddress(XTopsimple *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Axilites_BaseAddress + XTOPSIMPLE_AXILITES_ADDR_OUT_R_HIGH);
}

u32 XTopsimple_Get_out_r_TotalBytes(XTopsimple *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XTOPSIMPLE_AXILITES_ADDR_OUT_R_HIGH - XTOPSIMPLE_AXILITES_ADDR_OUT_R_BASE + 1);
}

u32 XTopsimple_Get_out_r_BitWidth(XTopsimple *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XTOPSIMPLE_AXILITES_WIDTH_OUT_R;
}

u32 XTopsimple_Get_out_r_Depth(XTopsimple *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XTOPSIMPLE_AXILITES_DEPTH_OUT_R;
}

u32 XTopsimple_Write_out_r_Words(XTopsimple *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XTOPSIMPLE_AXILITES_ADDR_OUT_R_HIGH - XTOPSIMPLE_AXILITES_ADDR_OUT_R_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->Axilites_BaseAddress + XTOPSIMPLE_AXILITES_ADDR_OUT_R_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XTopsimple_Read_out_r_Words(XTopsimple *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XTOPSIMPLE_AXILITES_ADDR_OUT_R_HIGH - XTOPSIMPLE_AXILITES_ADDR_OUT_R_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->Axilites_BaseAddress + XTOPSIMPLE_AXILITES_ADDR_OUT_R_BASE + (offset + i)*4);
    }
    return length;
}

u32 XTopsimple_Write_out_r_Bytes(XTopsimple *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XTOPSIMPLE_AXILITES_ADDR_OUT_R_HIGH - XTOPSIMPLE_AXILITES_ADDR_OUT_R_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->Axilites_BaseAddress + XTOPSIMPLE_AXILITES_ADDR_OUT_R_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XTopsimple_Read_out_r_Bytes(XTopsimple *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XTOPSIMPLE_AXILITES_ADDR_OUT_R_HIGH - XTOPSIMPLE_AXILITES_ADDR_OUT_R_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->Axilites_BaseAddress + XTOPSIMPLE_AXILITES_ADDR_OUT_R_BASE + offset + i);
    }
    return length;
}

void XTopsimple_InterruptGlobalEnable(XTopsimple *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XTopsimple_WriteReg(InstancePtr->Axilites_BaseAddress, XTOPSIMPLE_AXILITES_ADDR_GIE, 1);
}

void XTopsimple_InterruptGlobalDisable(XTopsimple *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XTopsimple_WriteReg(InstancePtr->Axilites_BaseAddress, XTOPSIMPLE_AXILITES_ADDR_GIE, 0);
}

void XTopsimple_InterruptEnable(XTopsimple *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XTopsimple_ReadReg(InstancePtr->Axilites_BaseAddress, XTOPSIMPLE_AXILITES_ADDR_IER);
    XTopsimple_WriteReg(InstancePtr->Axilites_BaseAddress, XTOPSIMPLE_AXILITES_ADDR_IER, Register | Mask);
}

void XTopsimple_InterruptDisable(XTopsimple *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XTopsimple_ReadReg(InstancePtr->Axilites_BaseAddress, XTOPSIMPLE_AXILITES_ADDR_IER);
    XTopsimple_WriteReg(InstancePtr->Axilites_BaseAddress, XTOPSIMPLE_AXILITES_ADDR_IER, Register & (~Mask));
}

void XTopsimple_InterruptClear(XTopsimple *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XTopsimple_WriteReg(InstancePtr->Axilites_BaseAddress, XTOPSIMPLE_AXILITES_ADDR_ISR, Mask);
}

u32 XTopsimple_InterruptGetEnabled(XTopsimple *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XTopsimple_ReadReg(InstancePtr->Axilites_BaseAddress, XTOPSIMPLE_AXILITES_ADDR_IER);
}

u32 XTopsimple_InterruptGetStatus(XTopsimple *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XTopsimple_ReadReg(InstancePtr->Axilites_BaseAddress, XTOPSIMPLE_AXILITES_ADDR_ISR);
}

