// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

// AXILiteS
// 0x00 : Control signals
//        bit 0  - ap_start (Read/Write/COH)
//        bit 1  - ap_done (Read/COR)
//        bit 2  - ap_idle (Read)
//        bit 3  - ap_ready (Read)
//        bit 7  - auto_restart (Read/Write)
//        others - reserved
// 0x04 : Global Interrupt Enable Register
//        bit 0  - Global Interrupt Enable (Read/Write)
//        others - reserved
// 0x08 : IP Interrupt Enable Register (Read/Write)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x0c : IP Interrupt Status Register (Read/TOW)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x10 : Data signal of ap_return
//        bit 31~0 - ap_return[31:0] (Read)
// 0x20 ~
// 0x2f : Memory 'output_M_real' (3 * 32b)
//        Word n : bit [31:0] - output_M_real[n]
// 0x30 ~
// 0x3f : Memory 'output_M_imag' (3 * 32b)
//        Word n : bit [31:0] - output_M_imag[n]
// 0x40 ~
// 0x7f : Memory 'input1_M_real' (15 * 32b)
//        Word n : bit [31:0] - input1_M_real[n]
// 0x80 ~
// 0xbf : Memory 'input1_M_imag' (15 * 32b)
//        Word n : bit [31:0] - input1_M_imag[n]
// 0xc0 ~
// 0xcf : Memory 'input2_M_real' (3 * 32b)
//        Word n : bit [31:0] - input2_M_real[n]
// 0xd0 ~
// 0xdf : Memory 'input2_M_imag' (3 * 32b)
//        Word n : bit [31:0] - input2_M_imag[n]
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XTOPADDER_AXILITES_ADDR_AP_CTRL            0x00
#define XTOPADDER_AXILITES_ADDR_GIE                0x04
#define XTOPADDER_AXILITES_ADDR_IER                0x08
#define XTOPADDER_AXILITES_ADDR_ISR                0x0c
#define XTOPADDER_AXILITES_ADDR_AP_RETURN          0x10
#define XTOPADDER_AXILITES_BITS_AP_RETURN          32
#define XTOPADDER_AXILITES_ADDR_OUTPUT_M_REAL_BASE 0x20
#define XTOPADDER_AXILITES_ADDR_OUTPUT_M_REAL_HIGH 0x2f
#define XTOPADDER_AXILITES_WIDTH_OUTPUT_M_REAL     32
#define XTOPADDER_AXILITES_DEPTH_OUTPUT_M_REAL     3
#define XTOPADDER_AXILITES_ADDR_OUTPUT_M_IMAG_BASE 0x30
#define XTOPADDER_AXILITES_ADDR_OUTPUT_M_IMAG_HIGH 0x3f
#define XTOPADDER_AXILITES_WIDTH_OUTPUT_M_IMAG     32
#define XTOPADDER_AXILITES_DEPTH_OUTPUT_M_IMAG     3
#define XTOPADDER_AXILITES_ADDR_INPUT1_M_REAL_BASE 0x40
#define XTOPADDER_AXILITES_ADDR_INPUT1_M_REAL_HIGH 0x7f
#define XTOPADDER_AXILITES_WIDTH_INPUT1_M_REAL     32
#define XTOPADDER_AXILITES_DEPTH_INPUT1_M_REAL     15
#define XTOPADDER_AXILITES_ADDR_INPUT1_M_IMAG_BASE 0x80
#define XTOPADDER_AXILITES_ADDR_INPUT1_M_IMAG_HIGH 0xbf
#define XTOPADDER_AXILITES_WIDTH_INPUT1_M_IMAG     32
#define XTOPADDER_AXILITES_DEPTH_INPUT1_M_IMAG     15
#define XTOPADDER_AXILITES_ADDR_INPUT2_M_REAL_BASE 0xc0
#define XTOPADDER_AXILITES_ADDR_INPUT2_M_REAL_HIGH 0xcf
#define XTOPADDER_AXILITES_WIDTH_INPUT2_M_REAL     32
#define XTOPADDER_AXILITES_DEPTH_INPUT2_M_REAL     3
#define XTOPADDER_AXILITES_ADDR_INPUT2_M_IMAG_BASE 0xd0
#define XTOPADDER_AXILITES_ADDR_INPUT2_M_IMAG_HIGH 0xdf
#define XTOPADDER_AXILITES_WIDTH_INPUT2_M_IMAG     32
#define XTOPADDER_AXILITES_DEPTH_INPUT2_M_IMAG     3

